# Change these first
owner: dismantl
repo: acab-status

sites:
  - name: Gitlab
    url: https://acab.enterprises
    icon: https://acab.enterprises/uploads/-/system/appearance/favicon/1/acablogosmall.png
  - name: Critical Frequency
    url: https://criticalfrequency.org
    icon: https://criticalfrequency.org/favicon-32x32.png
  - name: BPD Watch
    url: https://bpdwatch.com
    icon: https://bpdwatch.com/static/icons/favicon-32x32.png
  - name: Case Explorer
    url: https://mdcaseexplorer.com
    icon: https://mdcaseexplorer.com/favicon.ico
  - name: Open Justice Baltimore
    url: https://openjusticebaltimore.org
    icon: https://openjusticebaltimore.org/favicon-32x32.png
  - name: FORCE
    url: https://upsettingrapeculture.com
    icon: https://upsettingrapeculture.com/favicon-32x32.png
  - name: The Monument Quilt
    url: https://themonumentquilt.org
    icon: https://themonumentquilt.org/favicon.ico
  - name: The Monument Quilt (App)
    url: https://app.themonumentquilt.org
    icon: https://app.themonumentquilt.org/favicon.ico
  - name: Personal website
    url: https://disman.tl
  - name: Nextcloud
    url: https://nextcloud.acab.enterprises
    icon: https://nextcloud.acab.enterprises/core/img/favicon.ico
  - name: Analytics
    url: https://analytics.acab.enterprises
    icon: https://analytics.acab.enterprises/plugins/CoreHome/images/favicon.png
  - name: Mail
    url: $MAIL_URL
    icon: https://mail.acab.enterprises/favicon.ico
  - name: Plex
    url: https://plex.acab.enterprises/web/index.html
    icon: https://plex.acab.enterprises/web/favicon.ico
  - name: Torrent
    url: https://torrent.acab.enterprises
    icon: https://torrent.acab.enterprises/icons/deluge-32.png
  - name: Movies
    url: https://movies.acab.enterprises
    icon: https://movies.acab.enterprises/Content/Images/Icons/favicon-32x32.png
  - name: TV
    url: https://tv.acab.enterprises
    icon: https://tv.acab.enterprises/Content/Images/Icons/favicon-32x32.png
  - name: Jackett
    url: https://jackett.acab.enterprises
    icon: https://jackett.acab.enterprises/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.acab.enterprises
  # baseUrl: /your-repo-name
  logoUrl: https://acab.enterprises/uploads/-/system/appearance/logo/1/acablogo300.png
  name: ACAB Enterprises Status
  introTitle: "**ACAB Enterprises** status"
  introMessage: Check here for the status of ACAB Enterprises websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - dismantl
robotsText: "User-agent: * \n Disallow: /"
